name: marlin
description: 
version: 1.0.0
homepage: 
publish_to: none

environment:
  sdk: ^3.6.0

dependencies: 
  archive: ^4.0.7    
  unicode: ^1.1.8 
  logging: ^1.3.0
 
dev_dependencies:
  test: ^1.26.3

 

